"""Initial schema with compliance tables

Revision ID: 989ceebf408f
Revises: 
Create Date: 2025-12-06 10:04:44.547233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989ceebf408f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('page_range', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_code')
    )
    op.create_index(op.f('ix_compliance_sections_id'), 'compliance_sections', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_sections_section_code'), 'compliance_sections', ['section_code'], unique=False)
    op.create_table('compliance_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('basic_requirement', sa.Text(), nullable=True),
    sa.Column('applicability', sa.Text(), nullable=True),
    sa.Column('detailed_explanation', sa.Text(), nullable=True),
    sa.Column('instructions_for_reviewer', sa.Text(), nullable=True),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['compliance_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_questions_id'), 'compliance_questions', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_questions_question_code'), 'compliance_questions', ['question_code'], unique=False)
    op.create_index(op.f('ix_compliance_questions_applicability'), 'compliance_questions', ['applicability'], unique=False)
    op.create_table('indicators_of_compliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('indicator_text', sa.Text(), nullable=False),
    sa.Column('indicator_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['compliance_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_of_compliance_id'), 'indicators_of_compliance', ['id'], unique=False)
    op.create_table('possible_deficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('deficiency_text', sa.Text(), nullable=False),
    sa.Column('deficiency_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['compliance_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_possible_deficiencies_id'), 'possible_deficiencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_possible_deficiencies_id'), table_name='possible_deficiencies')
    op.drop_table('possible_deficiencies')
    op.drop_index(op.f('ix_indicators_of_compliance_id'), table_name='indicators_of_compliance')
    op.drop_table('indicators_of_compliance')
    op.drop_index(op.f('ix_compliance_questions_applicability'), table_name='compliance_questions')
    op.drop_index(op.f('ix_compliance_questions_question_code'), table_name='compliance_questions')
    op.drop_index(op.f('ix_compliance_questions_id'), table_name='compliance_questions')
    op.drop_table('compliance_questions')
    op.drop_index(op.f('ix_compliance_sections_section_code'), table_name='compliance_sections')
    op.drop_index(op.f('ix_compliance_sections_id'), table_name='compliance_sections')
    op.drop_table('compliance_sections')
    # ### end Alembic commands ###
